### ISSUE TITLE
Crash on the Claim page in production

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-governance#206]
This is on the latest production deployment (v40 from the Heroku deployment page)

I go to the production site at https://governance.ousd.com
My wallet is 0xD85A569F3C26f81070544451131c742283360400 and is eligible for the airdrop
I use admin tools to go the the claims page

=> I get an endless spinner and a bunch of errors in the JS console

Video: https://www.loom.com/share/b5a6ad41c52c4067a9233d68fa62e64d

JS console errors:
```
_app-8425ada72c0d16c7.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'balanceOf')
    at _app-8425ada72c0d16c7.js:1:1033496
    at s (main-1d8adce4d7e8417e.js:1:89184)
    at Generator._invoke (main-1d8adce4d7e8417e.js:1:88972)
    at P.forEach.e.<computed> [as next] (main-1d8adce4d7e8417e.js:1:89607)
    at l (_app-8425ada72c0d16c7.js:1:1032009)
    at o (_app-8425ada72c0d16c7.js:1:1032212)
    at _app-8425ada72c0d16c7.js:1:1032271
    at new Promise (<anonymous>)
    at _app-8425ada72c0d16c7.js:1:1032152
    at _app-8425ada72c0d16c7.js:1:1033619
_app-8425ada72c0d16c7.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'allowance')
    at _app-8425ada72c0d16c7.js:1:1034316
    at s (main-1d8adce4d7e8417e.js:1:89184)
    at Generator._invoke (main-1d8adce4d7e8417e.js:1:88972)
    at P.forEach.e.<computed> [as next] (main-1d8adce4d7e8417e.js:1:89607)
    at l (_app-8425ada72c0d16c7.js:1:1032009)
    at o (_app-8425ada72c0d16c7.js:1:1032212)
    at _app-8425ada72c0d16c7.js:1:1032271
    at new Promise (<anonymous>)
    at _app-8425ada72c0d16c7.js:1:1032152
    at _app-8425ada72c0d16c7.js:1:1034460
867-5b33616731c18a49.js:1 Can not fetch veOgv total supply: TypeError: Cannot read properties of undefined (reading 'totalSupply')
    at 867-5b33616731c18a49.js:1:6673
    at s (main-1d8adce4d7e8417e.js:1:89184)
    at Generator._invoke (main-1d8adce4d7e8417e.js:1:88972)
    at P.forEach.e.<computed> [as next] (main-1d8adce4d7e8417e.js:1:89607)
    at v (867-5b33616731c18a49.js:1:1600)
    at i (867-5b33616731c18a49.js:1:1803)
    at 867-5b33616731c18a49.js:1:1862
    at new Promise (<anonymous>)
    at 867-5b33616731c18a49.js:1:1743
    at 867-5b33616731c18a49.js:1:6957
(anonymous) @ 867-5b33616731c18a49.js:1
_app-8425ada72c0d16c7.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'totalSupply')
    at _app-8425ada72c0d16c7.js:1:1048024
    at s (main-1d8adce4d7e8417e.js:1:89184)
    at Generator._invoke (main-1d8adce4d7e8417e.js:1:88972)
    at P.forEach.e.<computed> [as next] (main-1d8adce4d7e8417e.js:1:89607)
    at l (_app-8425ada72c0d16c7.js:1:1046583)
```

**Comment by sparrowDom** [comment]
The problem is we are missing `OriginDollarGovernance` contract in `governance.mainnet.json` file. We have it on Rinkeby here: https://github.com/OriginProtocol/ousd-governance/blob/master/client/networks/governance.rinkeby.json#L2

**Comment by sparrowDom** [comment]
Some other contract artifacts are missing as well: 
- OriginDollarGovernance
- RewardsSource
- OgvStaking
- MandatoryDistributor
- OptionalDistributor

@DanielVF @tomlinton anybody know where we might fetch those addresses?

**Comment by sparrowDom** [comment]
except for the distributors this PR fixes it: https://github.com/OriginProtocol/ousd-governance/pull/209
